### ISSUE TITLE
SUNRGBD dataset

### ISSUE THREAD

**Issue by yjh576** [Na-Z/sess#10]
I can't find the folders sunrgbd_trainval/train_data_idx.txt or train_data_idx.txt, when I run extract_split.m. Could you give me some advice?

**Comment by Na-Z** [comment]
Hi,

If u can successfully run extract_split.m, it will generate these two files (i.e., train_data_idx.txt and val_data_idx.txt) under the folder of sunrgbd_trainval. 

Please read the [README.md](https://github.com/Na-Z/sess/blob/master/sunrgbd/README.md) and follow the instruction.
