### ISSUE TITLE
Visualization of sunrgbd and scannet

### ISSUE THREAD

**Issue by czy341181** [Na-Z/sess#11]
Hi, Can you provide the visual code for sunrgbd and scannet?  thanks!

**Comment by Na-Z** [comment]
Hi, you can use Meshlab to visualize the PLY files. Please refer to [dump_helper.py](https://github.com/Na-Z/sess/blob/f1bbb44ea6ed73bb71bce12f54ca9bc33746dce8/models/dump_helper.py) for the details.
