### ISSUE TITLE
Question about Autonomous Driving Datasets

### ISSUE THREAD

**Issue by MartinHahner** [Na-Z/sess#2]
Hi Na, 
congratulations on your nice work.
Unfortunately, I missed attending your live Q&A at Virtual CVPR.

I have a question regarding other datasets.
Given your expertise on VoteNet, do you think their/your pipeline also works on outdoor 3D Object Detection Datasets like  

- KITTI
- nuScenes
- Waymo Open Dataset
- ...

or have you even tried it yourself on such a dataset?

Greets, Martin

**Comment by Na-Z** [comment]
Hi Martin,

Thanks for your interest in our work. 

We haven't tried SESS on outdoor datasets yet, but we do have a plan to try it in the future.

As we mentioned in the paper, SESS is a model-agnostic framework. In this work, we adopt VoteNet as our backbone. Thus, if we would like to apply SESS on outdoor datasets, we should either make some modifications on VoteNet to make it work well on sparse LiDAR data (see some discussions [here](https://github.com/facebookresearch/votenet/issues/8)  and [here](https://github.com/facebookresearch/votenet/issues/53)) or adopt another 3D object detector that works well on LiDAR data as backbone.

Best, Na

**Comment by MartinHahner** [comment]
Thank you for your quick reply and for pointing me to the two discussion threads on the official VoteNet repository.
