### ISSUE TITLE
training other data sets

### ISSUE THREAD

**Issue by b-xie** [Na-Z/sess#4]
Thanks for your great work! Can I use your code to train other data sets?  Liking Kitti.  What needs to be changed? Thanks!

**Comment by Na-Z** [comment]
Sure. Please cite us if you use our code. 
For the use of SESS on outdoor datasets like Kitti, please kindly refer to discussion in https://github.com/Na-Z/sess/issues/2#issuecomment-653363550.

**Comment by b-xie** [comment]
Sure. Thanks again!

**Comment by AndyYuan96** [comment]
> Sure. Thanks again!

Hi, do you have the result on AD dataset like kitti, waymo or others?
