### ISSUE TITLE
an error when eval the model

### ISSUE THREAD

**Issue by zyoungDL** [Na-Z/sess#7]
Traceback (most recent call last):
  File "eval.py", line 100, in <module>
    test_transductive = FLAGS.transductive)
  File "/root/sess-master/scannet/scannet_detection_dataset.py", line 67, in __init__
    os.path.join(self.raw_data_path, labeled_sample_list)).readlines()]
AttributeError: 'ScannetDetectionDataset' object has no attribute 'raw_data_path'

**Comment by zyoungDL** [comment]
can you tell me the right path of the raw data? Thank you.

**Comment by Na-Z** [comment]
Hi, the path should be "ROOT_DIR + 'scannet/meta_data'". Pls see the latest commit.

**Comment by zyoungDL** [comment]
好的, 谢谢
